package vista;

import controlador.Ctrl_Categorias;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.Categorias;

/**
 *
 * @author yanni
 */
public class InternalFrmCategorias extends javax.swing.JInternalFrame {

    public InternalFrmCategorias() {
        initComponents();
        this.setSize(new Dimension(400, 200));
        this.setTitle("CATEGORIA NUEVA");
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnueva_categoria = new javax.swing.JTextField();
        btnguardar_categoria = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NUEVA CATEGORIA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" DESCRIPCION DE LA CATEGORIA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 20));

        txtnueva_categoria.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txtnueva_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 270, -1));

        btnguardar_categoria.setBackground(new java.awt.Color(255, 255, 255));
        btnguardar_categoria.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        btnguardar_categoria.setForeground(java.awt.Color.blue);
        btnguardar_categoria.setText("GUARDAR");
        btnguardar_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar_categoriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 120, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-elegant-wallpaper-preview.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardar_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar_categoriaActionPerformed
        // TODO add your handling code here:
        Categorias categorias = new Categorias();
        Ctrl_Categorias controlCategorias = new Ctrl_Categorias();

        //Validacion de campos vacios.
        if (txtnueva_categoria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Introduzca una Categoria Por Favor.");
        } else {
            if (!controlCategorias.ExisteCategorias(txtnueva_categoria.getText().trim())) {
                categorias.setDescripcion(txtnueva_categoria.getText().trim());
                if (controlCategorias.Guardar(categorias)) {
                    JOptionPane.showMessageDialog(null, "Categoria Guardada Exitosamente.");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Guardar.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "La Categoria Ya Esta Registrada.");
            }
        }

        //limpiar campos
        txtnueva_categoria.setText("");


    }//GEN-LAST:event_btnguardar_categoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar_categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextField txtnueva_categoria;
    // End of variables declaration//GEN-END:variables
}
